version: 2

models:
  - name: int_sale__cleaned_invoices
    description: "Intermediate cleaned table with enriched metrics and validations."
    columns:
      - name: revenue
        tests:
          - not_null
          - greater_than:
              value: 0
