version: 2

models:
  - name: fct_sales
    description: "Final fact table for reporting and dashboards"
    tests:
      - unique:
          column_name: order_id
      - not_null:
          column_name: order_id
