name: "ecommerce_project"
version: "1.0.0"
config-version: 2

profile: "default"

models:
  my_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
