config-version: 2

name: "sale"
version: "1.0"
profile: "sale"

model-paths: ["models"]

models:
  sale:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
    report:
      +materialized: view
