version: 2

models:
  - name: stg_sale__invoices
    description: "Staging layer for sale invoices. Cleans and standardizes raw data."
    columns:
      - name: order_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
          - greater_than:
              value: 0
      - name: amount
        tests:
          - not_null
          - greater_than:
              value: 0
